server:
  port: 0

spring:
  application:
    name: tollrate-service

eureka:
  client:
    #service-url: localhost:8761
    register-with-eureka: true
    fetch-registry: false
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost