spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: toll-servicev1
        uri: lb://tollrate-service
        predicates:
        - Method=GET
        - Path=/v1/tollrate/{stationid}
        filters:
        - SetPath=/tollrate/{stationid}
        - AddResponseHeader=X-Expiring-Service, please use v2
      - id: toll-servicev2
        uri: lb://tollrate-service
        predicates:
        - Path=/v2/tollrate/{stationid}
        filters:
        - SetPath=/tollratev2/{stationid}


eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost

server:
  port: 8080
