spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
      - id: toll-service
        uri: http://localhost:49880
        predicates:
        - Method=GET
        - Path=/tollrate/{stationid}
        - Query=apicaller

server:
  port: 8080
