spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: toll-service
        uri: lb://tollrate-service
        predicates:
        - Method=GET
        - Path=/tollrate/{stationid}
        - Query=apicaller

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost

server:
  port: 8080
