spring:
  application:
    name: s1rates
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: master
      username: pluralsight
      password: pluralsight

encrypt:
  key: ABCDEFGHIJKLMNOPQRSTUVWXYZ

management:
  endpoints:
    web:
      exposure:
        include: refresh