spring:
  application:
    name: tollrate-ui

eureka:
  client:
    #service-url: localhost:8761
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  timelimiter:
    instances:
      tollrate-cb:
        timeout-duration: 4s
  circuitbreaker:
    instances:
      tollrate-cb:
        register-health-indicator: true
        sliding-window-size: 3
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 3
        slow-call-duration-threshold: 2500
        slow-call-rate-threshold: 50
        wait-duration-in-open-state: 20000