spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/jayaprakash-charugundla/spring-cloud-config-wa-tolls
          search-paths:
            - station*
          repos:
            perf:
              pattern: '*/perf'
              uri: https://github.com/jayaprakash-charugundla/spring-cloud-config-wa-tolls-perf
              search-paths:
                - station*
  security:
    user:
      name: pluralsight
      password: pluralsight

server:
  port: 8888
encrypt:
  key: ABCDEFGHIJKLMNOPQRSTUVWXYZ
