spring:
  application:
    name: fastpass-ui
  cloud:
    stream:
      bindings:
        generatetollcharge-out-0:
          destination: tolltopic
          content-type: application/json
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    #service-url: localhost:8761
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost

server:
  port: 8082

